Parameters:
  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String
  
  NameBucket:
    Description: Unique name of the S3 bucket where stores the files to deploy
    Type: String
    Default: s3-bucket

Resources:

  bucketS3:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref NameBucket
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
      DeletionPolicy: Delete

 
      

    
